apiVersion: v1
kind: Service
metadata:
  name: elimu
  namespace: techsavanna-saas
  labels:
    app: elimu
    app.kubernetes.io/name: elimu
    app.kubernetes.io/part-of: techsavanna-saas
spec:
  type: ClusterIP
  selector:
    app: elimu
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
